[package]
name = "egg-coin"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
Std = "0x1"
EggCoin = "0xd10801b04e73470295b33c1f0c372aee13e341c45228560d74b9c91ae670fceb"

